### ISSUE TITLE
New rustdesk api

### ISSUE THREAD

**Issue by Cchumi** [kongbg/rust-api-server#1]
Hi 
First of all thanks for your api server great job really. 
Do you know why with the new version just released the ai server don't work ? 
I received bad response from rustdesk client.  

Thank you. 

Cchumi

**Comment by kongbg** [comment]
The port is working on windows and Android. If you device is macOS, you can change the server port. But i donot know the port of macOS.

**Comment by kongbg** [comment]
> Hi First of all thanks for your api server great job really. Do you know why with the new version just released the ai server don't work ? I received bad response from rustdesk client.
> 
> Thank you.
> 
> Cchumi

The port is working on windows and Android. If you device is macOS, you can change the server port. But i donot know the port of macOS.

**Comment by Cchumi** [comment]
Hi thanks for your answer. 
The port work well on macos. I see communication between rustdesk client and api server. But it looks since the new client version they changed the incomming format.
It was working well with 1.9.

Thanks a lot

CcHuMi

**Comment by Sebshino** [comment]
Good morning,

I also try to install the API server with the latest RustDesk versions and I get a "failed bad response from server" message, if I leave the window, on the server terminal I get the following error:

  TypeError: Cannot read properties of undefined (reading 'id')
       at addAb (file:///home/seb/rust-api-server/src/controllers/rust.js:152:29)
       at dispatch (/home/seb/rust-api-server/node_modules/koa-compose/index.js:42:32)
       at /home/seb/rust-api-server/node_modules/koa-router/lib/router.js:425:16
       at dispatch (/home/seb/rust-api-server/node_modules/koa-compose/index.js:42:32)
       at /home/seb/rust-api-server/node_modules/koa-compose/index.js:34:12
       at dispatch (/home/seb/rust-api-server/node_modules/koa-router/lib/router.js:430:31)
       at dispatch (/home/seb/rust-api-server/node_modules/koa-compose/index.js:42:32)
       at bodyParser (/home/seb/rust-api-server/node_modules/koa-bodyparser/index.js:91:11)
       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by kongbg** [comment]
v1.2.3 is ok
